apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-argo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Kristof-oe/project_2
    targetRevision: HEAD
    path: main
  destination:
    server: https://kubernetes.deafult.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
