apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.fastapi }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.fastapi }}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Values.fastapi }}
    spec:
      containers:
      - name:  {{ .Values.fastapi }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetport }}
