apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.fastapi }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.fastapi }}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Values.fastapi }}
    spec:
      containers:
      - name:  {{ .Values.fastapi }}
        image: "{{ .Values.image.repository }}/{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetport }}
        env:
          # - name: POSTGRES_HOST
          #   value: track-processing-postgresql

          # - name: POSTGRES_DB
          #   valueFrom:
          #     secretKeyRef:
          #       name: track-processing-postgresql
          #       key: postgresql-database

          # - name: POSTGRES_USER
          #   valueFrom:
          #     secretKeyRef:
          #       name: track-processing-postgresql
          #       key: postgresql-username

          #  - name: POSTGRES_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: track-processing-postgresql
          #       key: postgresql-password

          - name: DATABASE_URL
            value: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@track-processing-postgresql:5432/{{ .Values.postgresql.auth.database }}"

            
