apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
    nano: blazing
reasource:
    - secret.yaml
    - deployment.yaml
    - service.yaml
    - namespace.yaml
    
helmCharts:
    - name: postgresql
      namespace: blazing
      releaseName: postgresql
      repo: https://charts.bitnami.com/bitnami
      version: 16.1.2
      valueFile: values.yaml